# Generated by Django 5.2.7 on 2026-04-04 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_module', '0006_remove_teacherprofile_monthly_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_profile', 'date', 'marked_by')},
        ),
    ]
